# Welcome to Jekyll!
#

# Site settings
title: Dayoung Kim
description: |
  PhD candidate in linguistics at the University of California, San Diego
owner: Dayoung Kim
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "dykim515.github.io" # the base hostname & protocol for your site
social:
 # twitter: 
#github: https://github.com/dykim515
 # linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/dayoung.k.kim
  google-plus-square: https://plus.google.com/u/0/+dykim515
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
